from codeview.block.valueblock import ValueBlock
from codeview.block.ifblock import IfBlock
from codeview.block.ifelseblock import IfElseBlock
from codeview.block.methodblock import MethodBlock
from codeview.block.operationblock import OperationBlock
import pygame
pygame.font.init()
#Blockdict with every possible block
#Notation {(name, type): Block}
block_dict = {
    ("+", "operation"): OperationBlock("+"),
    ("-", "operation"): OperationBlock("-"),
    ("*", "operation"): OperationBlock("*"),
    ("/", "operation"): OperationBlock("/"),
    ("%", "operation"): OperationBlock("%"),
    ("^", "operation"): OperationBlock("^"),
    ("and", "operation"): OperationBlock("and"),
    ("or", "operation"): OperationBlock("or"),
    ("not", "operation"): OperationBlock("not",number_of_operators=1),
    ("=", "operation"): OperationBlock("="),
    ("!=", "operation"): OperationBlock("!="),
    ("<", "operation"): OperationBlock("<"),
    (">", "operation"): OperationBlock(">"),
    ("<=", "operation"): OperationBlock("<="),
    (">=", "operation"): OperationBlock(">="),
    ("getOwnWidth", "value"): ValueBlock("getOwnWidth","getOwnWidth", parameters=()),
    ("getOwnHeight", "value"): ValueBlock("getOwnHeight","getOwnHeight", parameters=()),
    ("getRandom", "value"): ValueBlock("getRandom","getRandom", parameters=("min", "max")),
    ("getX", "value"): ValueBlock("getOwnX","getX", parameters=()),
    ("getY", "value"): ValueBlock("getOwnY","getY", parameters=()),
    ("getPos", "value"): ValueBlock("getOwnPosition","getPos", parameters=()),
    ("getOpX", "value"): ValueBlock("getOpponentX","getOpX", parameters=()),
    ("getOpY", "value"): ValueBlock("getOpponentY","getOpY", parameters=()),
    ("getOpPos", "value"): ValueBlock("getOpponentPosition","getOpPos", parameters=()),
    ("getOpMovementX", "value"): ValueBlock("getOpponentMovementX","getOpMovementX", parameters=()),
    ("getOpMovementY", "value"): ValueBlock("getOpponentMovementY","getOpMovementY", parameters=()),
    ("getOpDistance", "value"): ValueBlock("getOpponentDistance","getOpDistance", parameters=()),
    ("getDistance", "value"): ValueBlock("getDistanceTo","getDistance", parameters=("X", "Y")),
    ("getDistance", "value"): ValueBlock("getDistanceTo","getDistance", parameters=("position",)),
    ("getOwnMaxTimeToNextAttack", "value"): ValueBlock("getOwnMaxTimeToNextAttack","getOwnMaxTimeToNextAttack", parameters=()),
    ("getOpMaxTimeToNextAttack", "value"): ValueBlock("getOpponentMaxTimeToNextAttack","getOpMaxTimeToNextAttack", parameters=()),
    ("getOwnMaxTimeToNextAttackt", "value"): ValueBlock("getOwnMaxTimeToNextAttackt","getOwnMaxTimeToNextAttackt", parameters=()),
    ("getOpTimeToNextAttack", "value"): ValueBlock("getOpponentTimeToNextAttack", "getOpTimeToNextAttack", parameters=()),
    ("getLifes", "value"): ValueBlock("getLifes","getLifes", parameters=()),
    ("getOpLifes", "value"): ValueBlock("getOpponentLifes","getOpLifes", parameters=()),
    ("destinationReached", "value"): ValueBlock("destinationReached","destinationReached", parameters=()),
    ("onPos", "value"): ValueBlock("onPosition","onPos", parameters=("X", "Y"),),
    ("onPos", "value"): ValueBlock("onPosition","onPos", parameters=("Position",)),
    ("onX", "value"): ValueBlock("onX","onX", parameters=("X",)),
    ("onY", "value"): ValueBlock("onY","onY", parameters=("Y",)),
    ("getArenaWidth", "value"): ValueBlock("getArenaWidth","getArenaWidth", parameters=()),
    ("getArenaHeight", "value"): ValueBlock("getArenaHeight","getArenaHeight", parameters=()),
    ("onBorder", "value"): ValueBlock("onBorder","onBorder", parameters=()),
    ("onLeftBorder", "value"): ValueBlock("onLeftBorder","onLeftBorder", parameters=()),
    ("onRightBorder", "value"): ValueBlock("onRightBorder","onRightBorder", parameters=()),
    ("onTopBorder", "value"): ValueBlock("onTopBorder","onTopBorder", parameters=()),
    ("onBottomBorder", "value"): ValueBlock("onBottomBorder","onBottomBorder", parameters=()),
    ("", "if"): IfBlock(),
    ("", "ifelse"): IfElseBlock(),
    ("print", "method"): MethodBlock("print","print", parameters=("value", )),
    ("goto0", "method"): MethodBlock("goTo","goto", parameters=("x", "y")),
    ("goto1", "method"): MethodBlock("goTo","goto", parameters=("position", )),
    ("move0", "method"): MethodBlock("move","move", parameters=("x", "y")),
    ("move1", "method"): MethodBlock("move","move", parameters=("movement",)),
    ("shoot0", "method"): MethodBlock("shoot","shoot", parameters=()),
    ("shoot1", "method"): MethodBlock("shoot","shoot", parameters=("moveX", "moveY")),
    ("shoot2", "method"): MethodBlock("shoot","shoot", parameters=("movement", )),
    ("shootTo0", "method"): MethodBlock("shootTo","shootTo", parameters=("X", "Y")),
    ("shootTo1", "method"): MethodBlock("shootTo","shootTo", parameters=("position", )),
}